version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exampleDb
      MYSQL_USER: flaskapp
      MYSQL_PASSWORD: flaskapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  workprofile:
    build:
      context: ../
    container_name: workprofile
    environment:
      DB_HOST: mysql
      DB_USER: flaskapp
      DB_PASS: flaskapp
      DB_NAME: exampleDb
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    networks:
      - backend
      - frontend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - workprofile
    networks:
      - frontend

volumes:
  mysql_data:

networks:
  frontend:
  backend:
